language: cpp

sudo: required

before_install:
  - pip install --user cpp-coveralls

addons:
    sonarcloud:
      organization: "1lae"
      token:
         secure: "997037cc3da8ae31f9918e4c3d92a5df42c89dd0"
    apt:
      sources:
      - ubuntu-toolchain-r-test
      packages:
      - gcc-5
      - g++-5

script:
  - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc
  - sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-5 /usr/bin/g++
  - gcc --version
  - g++ --version
  - qmake
  - make
  - ./tests/tests


after_success:
  - coveralls --root . -E ".*external.*" -E ".*tests.*"
  - build-wrapper-linux-x86-64 --out-dir bw-output make clean all
  - sonar-scanner -Dsonar.verbose=true -X

cache:
 directories:
 - '$HOME/.sonar/cache'

notifications:
  email: false
