language:
  - cpp

sudo: required
dist: tusty

compiler: gcc

before_script:
    - sudo apt-get install build-essential
    - sudo apt-get install cmake
    - sudo apt-get install libboost-all-dev
    - sudo apt-get install libopencv-dev
    - sudo apt-get install libeigen3-dev

before_install:
  - pip install --user cpp-coveralls

addons:
  sonarcloud:
    organization: "1lae"
    token:
        secure: "997037cc3da8ae31f9918e4c3d92a5df42c89dd0"


script:
  - qmake
  - make
  - ./tests/tests

after_success:
  - coveralls --root . -E ".*external.*" -E ".*tests.*"
  - build-wrapper-linux-x86-64 --out-dir bw-output make clean all
  - sonar-scanner -Dsonar.verbose=true -X

cache:
 directories:
 - '$HOME/.sonar/cache'

notifications:
  email: false
