language: cpp

sudo: required

before_install:
  - pip install --user cpp-coveralls

install:
    - sudo apt update
    - sudo apt-get upgrade
    - sudo apt-get install build-essential cmake git libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev
    - sudo apt-get install python3.5-dev python3-numpy libtbb2 libtbb-dev
    - sudo apt-get install libjpeg-dev libpng-dev libtiff5-dev libjasper-dev libdc1394-22-dev libeigen3-dev libtheora-dev libvorbis-dev libxvidcore-dev libx264-dev sphinx-common libtbb-dev yasm libfaac-dev libopencore-amrnb-dev libopencore-amrwb-dev libopenexr-dev libgstreamer-plugins-base1.0-dev libavutil-dev libavfilter-dev libavresample-dev
    - sudo -s
    - cd /opt
    - git clone https://github.com/Itseez/opencv.git
    - git clone https://github.com/Itseez/opencv_contrib.git
    - cd opencv
    - mkdir release
    - cd release
    - cmake -D BUILD_TIFF=ON -D WITH_CUDA=OFF -D ENABLE_AVX=OFF -D WITH_OPENGL=OFF -D WITH_OPENCL=OFF -D WITH_IPP=OFF -D WITH_TBB=ON -D BUILD_TBB=ON -D WITH_EIGEN=OFF -D WITH_V4L=OFF -D WITH_VTK=OFF -D BUILD_TESTS=OFF -D BUILD_PERF_TESTS=OFF -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local -D OPENCV_EXTRA_MODULES_PATH=/opt/opencv_contrib/modules /opt/opencv/
    - make -j4
    - make install
    - ldconfig
    - exit
    - cd /home/travis/build/1LAE/Rekey/
    - pkg-config --modversion opencv



addons:
    apt:
      sources:
      - ubuntu-toolchain-r-test
      packages:
      - gcc-7
      - g++-7
    sonarcloud:
      organization: "1lae"
      token:
         secure: "997037cc3da8ae31f9918e4c3d92a5df42c89dd0"

script:
  - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-7 /usr/bin/gcc
  - sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-7 /usr/bin/g++
  - gcc --version
  - g++ --version
  - qmake
  - make
  - ./tests/tests


after_success:
  - coveralls --root . -E ".*external.*" -E ".*tests.*"
  - build-wrapper-linux-x86-64 --out-dir bw-output make clean all
  - sonar-scanner -Dsonar.verbose=true -X

cache:
 directories:
 - '$HOME/.sonar/cache'

notifications:
  email: false
