language: cpp
compiler: g++

before_install:
  - pip install --user cpp-coveralls
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - sudo apt-get https://github.com/opencv/opencv.git
 

addons:
    sonarcloud:
      organization: "1lae"
      token:
         secure: "997037cc3da8ae31f9918e4c3d92a5df42c89dd0"



script:
  - qmake
  - make
  - ./tests/tests


after_success:
  - coveralls --root . -E ".*external.*" -E ".*tests.*"
  - build-wrapper-linux-x86-64 --out-dir bw-output make clean all
  - sonar-scanner -Dsonar.verbose=true -X

cache:
 directories:
 - '$HOME/.sonar/cache'

notifications:
  email: false
