language: cpp

sudo: required

before_install:
  - pip install --user cpp-coveralls

install:
    - sudo apt update
    - mkdir ./temp
    - cd temp/
    - wget https://rpmfind.net/linux/openmandriva/4.0/repository/x86_64/main/release/lib64dc1394_22-2.2.5-1-omv4000.x86_64.rpm
    - rpm lib64dc*
    - cd ..


addons:
    apt:
      sources:
      - ubuntu-toolchain-r-test
      packages:
      - gcc-7
      - g++-7
    sonarcloud:
      organization: "1lae"
      token:
         secure: "997037cc3da8ae31f9918e4c3d92a5df42c89dd0"

script:
  - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-7 /usr/bin/gcc
  - sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-7 /usr/bin/g++
  - gcc --version
  - g++ --version
  - qmake
  - make
  - ./tests/tests


after_success:
  - coveralls --root . -E ".*external.*" -E ".*tests.*"
  - build-wrapper-linux-x86-64 --out-dir bw-output make clean all
  - sonar-scanner -Dsonar.verbose=true -X

cache:
 directories:
 - '$HOME/.sonar/cache'

notifications:
  email: false
